"""Run: python scripts/prepare_volare.py. Local inputs only; no data downloads."""

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import platform
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd
from volare_data import (
    MEASURES, SYMBOLS, RULES, availability_table, coverage_table,
    make_panel, quality_flags, validate_source,
)


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def csv_save(frame, path, index=False):
    frame.to_csv(path, index=index, date_format="%Y-%m-%d", na_rep="", float_format="%.17g")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=ROOT / "datasets/realized_variance_futures.csv")
    parser.add_argument("--output", type=Path, default=ROOT / "datasets/processed/volare")
    parser.add_argument("--reports", type=Path, default=ROOT / "reports/volare")
    args = parser.parse_args()
    source_hash = sha256(args.input)
    original = pd.read_csv(args.input)
    data = validate_source(original)
    panels = {measure: make_panel(data, measure) for measure in MEASURES}
    flags = quality_flags(data)
    calendar = availability_table(data)
    coverage = coverage_table(data, panels)
    flow = pd.DataFrame([
        {"measure": measure, "date_union": len(panel),
         "valid_es": int(panel[f"log_{measure}_scaled_ES"].notna().sum()),
         "valid_es_cl": int(panel[[f"log_{measure}_scaled_{s}" for s in ("ES", "CL")]].notna().all(axis=1).sum()),
         "valid_all_five": int(panel[[f"log_{measure}_scaled_{s}" for s in SYMBOLS]].notna().all(axis=1).sum()),
         "rows_deleted": 0}
        for measure, panel in panels.items()
    ])

    # Refuse configurations that could overwrite the source input.
    destinations = [args.output / f"volare_{m}.csv" for m in MEASURES]
    destinations += [args.reports / f for f in (
        "quality_flags.csv", "availability.csv", "coverage.csv", "sample_flow.csv",
        "provenance.json", "DATA_QUALITY_REPORT.md")]
    if args.input.resolve() in [p.resolve() for p in destinations]:
        raise ValueError("Output path would overwrite input")
    if args.output.resolve() == args.reports.resolve():
        raise ValueError("Keep panels and audit reports in separate directories")
    args.output.mkdir(parents=True, exist_ok=True)
    args.reports.mkdir(parents=True, exist_ok=True)
    for measure, panel in panels.items():
        csv_save(panel, args.output / f"volare_{measure}.csv", index=True)
    for frame, name in [(flags, "quality_flags"), (calendar, "availability"),
                        (coverage, "coverage"), (flow, "sample_flow")]:
        csv_save(frame, args.reports / f"{name}.csv")

    metadata = {
        "prepared_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_file": args.input.name, "source_sha256": source_hash,
        "source_downloaded_at": None,
        "source_download_note": "Historical download time is not recorded; preparation time is not retrieval time.",
        "documentation": "https://volare.unime.it/documentation",
        "symbols_in_source": sorted(original["symbol"].unique().tolist()),
        "selected_symbols": list(SYMBOLS), "input_rows": len(original),
        "selected_rows": len(data), "date_start": str(data.date.min().date()),
        "date_end": str(data.date.max().date()),
        "transform": {"scaled_variance": "variance * 10000", "logged_variance": "natural log of scaled variance when positive"},
        "calendar": "union of observed dates; not a verified exchange calendar",
        "rules": RULES, "rules_purpose": "fixed review flags, not deletion or trained thresholds",
        "deletions": 0, "imputation": False, "anomalies_corrected": False,
        "python": platform.python_version(), "pandas": pd.__version__, "numpy": np.__version__,
        "code_sha256": {p.name: sha256(p) for p in (Path(__file__), ROOT / "volare_data.py")},
        "output_sha256": {p.name: sha256(p) for p in destinations if p.suffix == ".csv"},
    }
    (args.reports / "provenance.json").write_text(json.dumps(metadata, indent=2) + "\n")

    def table(frame):
        # Avoid an optional tabulate dependency.
        return "\n".join([
            "| " + " | ".join(frame.columns) + " |",
            "| " + " | ".join(["---"] * len(frame.columns)) + " |",
            *["| " + " | ".join(str(v) for v in row) + " |" for row in frame.itertuples(index=False, name=None)],
        ])

    missing = int((~calendar.source_observed).sum())
    counts = flags.groupby("symbol").size().reindex(SYMBOLS, fill_value=0)
    report = f"""# VOLARE data preparation and quality report

Generated by `scripts/prepare_volare.py`. Re-running replaces this report and the
generated flags; store human decisions separately in `datasets/volare_review_decisions.csv`.

## Current status

**Prepared and checked for structure; not yet approved for final estimation.**

- Source: `{args.input.name}`; SHA-256 `{source_hash}`.
- Source download date: unknown. See `provenance.json` for preparation time.
- Selected records: **{len(data):,}**, across {len(SYMBOLS)} futures.
- Dates: **{data.date.min().date()} to {data.date.max().date()}**.
- Original values and observations retained; no filling, clipping or deletion.
- Review flags: **{len(flags)} asset-date records**. These are candidates for
  investigation, not confirmed data errors. They remain in both panels.
- **{missing} absent asset-date combinations** relative to the union of source
  dates. Absence may reflect a holiday, a different session schedule, delayed
  coverage or missing data. This audit does not classify exchange holidays.

## Coverage

{table(coverage.assign(first_date=coverage.first_date.dt.strftime('%Y-%m-%d'), last_date=coverage.last_date.dt.strftime('%Y-%m-%d')))}

## Available samples (counts only, not automatic filtering)

{table(flow)}

Each panel contains the full date union. Blank entries retain absence/invalid log
inputs. Dates where all required values exist are counted above but are not
automatically selected: resolving the intended session calendar is still required.
The first variance observation is retained; no return calculation forces its loss.

## Review flags by instrument

{table(counts.rename('flagged_asset_dates').rename_axis('symbol').reset_index())}

`quality_flags.csv` contains prices, RK/RV5/subsampled RV5 and a reason for each
flag. Fixed screens are RK/RV5 outside [0.1, 10], a low below 75% of both open/close,
a high above 125% of both open/close, an absolute unadjusted close log return above
20%, inconsistent OHLC, missing values, and nonpositive prices/variances.

These thresholds are transparent screening choices, not established cleaning
standards, and are not fitted to the full sample. Genuine crisis moves and
contract-roll gaps can be flagged. Screens are not exhaustive: unflagged does not
mean verified. Ratios compare estimators without assuming either is ground truth.

## How to use the prepared files

- `volare_rk.csv`: original RK, RK × 10,000 and log(RK × 10,000), with dates.
- `volare_rv5.csv`: the corresponding RV5 quantities on the same dates.
- `availability.csv`: explicit observation/measure availability for every date and asset.
- `provenance.json`: inputs, hashes, transformations, versions and output hashes.

Both measures are variances. Neither is annualised by this pipeline. Closing
returns are calculated only to flag potential anomalies/rolls and are not included
as prepared modelling returns. The panels have no lagged or future target columns.

## Next actions before estimation

1. Review ES/CL flags first; validate using another source or underlying quotes.
   Record unresolved cases honestly; do not convert flags directly into deletions.
2. Resolve session boundaries, holidays and gaps before creating lags/forecasts.
3. Confirm whether the project retains the interest-rate hypothesis; these files
   contain no rates. Finalise the split and information cutoff before tuning.
4. Use explicit measure/asset choices. Compare models on common target dates.

The old `volatility_model_QTFE_data.csv` is retained for reference; its current
version has RV5 columns but no date column. The current VAR notebook still
constructs RK. Neither is silently overwritten by this preparation command.
"""
    (args.reports / "DATA_QUALITY_REPORT.md").write_text(report)
    if sha256(args.input) != source_hash:
        raise RuntimeError("Source changed while preparing data; rerun from a fixed snapshot")
    print(f"Saved RK and RV5 panels: {len(panels['rk'])} dates each, no rows deleted.")
    print(f"Flagged {len(flags)} asset-date records; {missing} absent asset-date combinations.")
    print(f"Read: {args.reports / 'DATA_QUALITY_REPORT.md'}")


if __name__ == "__main__":
    main()
